apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-pavan-deployment
  labels:
    app: hello-pavan
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-pavan
  template:
    metadata:
      labels:
        app: hello-pavan
    spec:
      containers:
        - name: hello-pavan
          image: pavanreddych/hello-pavan-cicd:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080  # internal app port
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 8
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: hello-pavan-service
spec:
  selector:
    app: hello-pavan
  ports:
    - name: http
      port: 8082        # Service port inside the cluster
      targetPort: 8080  # Maps to container’s internal port
      nodePort: 30082   # Optional: external port on the host
  type: NodePort
